version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432" # exposes port 5432 to your vps machine
  graphql-engine:
    image: hasura/graphql-engine:v1.3.1
    depends_on:
    - "postgres"
    restart: always
    ports:
    - "8080:8080"
    environment:
      # database url to connect
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    command:
    - graphql-engine
    - serve
volumes:
  db_data:
