CREATE TABLE BOXES (
  ID SERIAL NOT NULL PRIMARY KEY,
  BOX_ID text NOT NULL UNIQUE,
  CABINET_ID text UNIQUE
);

CREATE TABLE SLOTS (
  ID SERIAL NOT NULL PRIMARY KEY,
  SLOT text NOT NULL UNIQUE,
  FILLED BOOL DEFAULT FALSE
);

CREATE TABLE films (
  ID SERIAL NOT NULL PRIMARY KEY,
  SLOT text,
  BOX text,
  CONSTRAINT slot_constraint
  FOREIGN KEY (SLOT)
  REFERENCES SLOTS (SLOT),
  CONSTRAINT box_constraint
  FOREIGN KEY (BOX)
  REFERENCES BOXES (BOX_ID)
);